obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[100, 100], [100, -100], [-100, -100], [-100, 100]]
inflation_radius: 0.65

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: camera, data_type: PointCloud2, topic: /point_cloud, marking: true, clearing: true}
