obstacle_range: 8.0
raytrace_range: 10.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.2
inflation_radius: 0.2

observation_sources: point_cloud_sensor

point_cloud_sensor: 
    sensor_frame: camera_link
    data_type: PointCloud2
    topic: /virat/point_cloud
    marking: true
    clearing: true
